name: build latest on push to master and release
on:
  push:
    branches:
    - master
    - release/*
jobs:
  operator-sdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: operator-sdk
      uses: ./.github/action/operator-sdk
      with:
        args: build lightbend-docker-registry.bintray.io/lightbend/akkacluster-operator-certified:latest
    - name: bintray login
      run: docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: push to bintray
      run: docker push lightbend-docker-registry.bintray.io/lightbend/akkacluster-operator-certified:latest
    - name: goreportcard
      uses: ./.github/action/curl
      with:
        args: -d repo=github.com/lightbend/akka-cluster-operator https://goreportcard.com/checks
